// Generated by https://quicktype.io

export interface Ticket {
  id: number;
  userId: string;
  status: string;
  comment?: null;
  courses: number[];
  date: string;
  startTime: string;
  endTime: string;
  min: number;
  max: number;
  p07: boolean;
  createdAt: string;
}
