// Generated by https://quicktype.io

export interface User {
  id: string;
  email: string;
  name: string;
  createdAt: string;
  isAdmin: boolean;
  tickets: Ticket[];
}

export interface Ticket {
  id: number;
  userId: string;
  status: string;
  comment: null | string;
  courses: number[];
  date: string;
  startTime: string;
  endTime: string;
  min: number;
  max: number;
  p07: boolean;
  createdAt: string;
  attempt: number;
  searches: Search[];
}

export interface Search {
  id: number;
  ticketId: number;
  comments: string;
  status: string;
  createdAt: string;
  response: Response | null;
}

export interface Response {
  id: number;
  ReservationName: string;
  Location: string;
  ScheduledTime: string;
  NumberOfPlayers: number;
  ReservationFee: string;
  TotalPrice: string;
  CancellationDeadline: string;
  ConfirmationNumber: string;
  IsSuccessful: boolean;
  StatusText: string;
  SponsorName: string;
  CourseName: string;
  City: string;
  State: string;
  Country: string;
  OrderID: string;
  Tax: string;
  SKU: string;
  ProductName: string;
  UnitPrice: string;
  Quantity: number;
  CaptainTeeTimeConflicts: null;
  CaptainTeeTimeConflictsFound: boolean;
  CaptainTeeTimeConflictMode: number;
  PartnerTeeTimeConflicts: null;
  PartnerTeeTimeConflictsFound: boolean;
  PartnerTeeTimeConflictMode: number;
  searchId: number;
}
